#ifndef PERIPHERAL_CONFIG_H
#define PERIPHERAL_CONFIG_H

// Motion (MPU9250)
#define MOTION_I2C_PORT I2C_NUM_1
#define MOTION_I2C_SDA 21
#define MOTION_I2C_SCL 22

// Display (ILI9341)
#define DISPLAY_PIN_MOSI 23
#define DISPLAY_PIN_CLK  18
#define DISPLAY_PIN_CS   14
#define DISPLAY_PIN_DC   27
#define DISPLAY_PIN_RST  33
#define DISPLAY_PIN_BCKL 32

// Input (Gameboy FACE)
#define INPUT_I2C_PORT I2C_NUM_2


#endif